export type Language = 'tl' | 'en'

export type GuideStep = {
  shortTitle: Record<Language, string>
  title: Record<Language, string>
  intro: Record<Language, string>
  bullets: Record<Language, string[]>
  note?: Record<Language, string>
  link?: {
    href: string
    label: Record<Language, string>
  }
}

export const steps: GuideStep[] = [
  {
    shortTitle: { tl: 'Suriin', en: 'Check' },
    title: { tl: 'Alamin kung kailangan mong kumuha ng kurso', en: 'Check whether you need to take the course' },
    intro: {
      tl: 'Karaniwang kailangan ang kurso para sa ilang long-term o permanent residence permit na ibinigay mula 1 Enero 2021.',
      en: 'The course is generally required for certain long-term or permanent residence permits issued from 1 January 2021.',
    },
    bullets: {
      tl: [
        'Dapat makumpleto ito sa loob ng isang taon mula sa pagkuha ng residence permit.',
        'Hindi ito naaangkop sa EU citizens at kanilang family members.',
        'May mga exemption ayon sa edad, uri ng permit at government programme.',
      ],
      en: [
        'It must be completed within one year of collecting the residence permit.',
        'It does not apply to EU citizens and their family members.',
        'There are exemptions based on age, permit type and government programme.',
      ],
    },
    note: {
      tl: 'Kung hindi ka sigurado, gamitin ang opisyal na orientation quiz. Gabay lamang ito at hindi legal na pagsusuri.',
      en: 'If you are unsure, use the official orientation quiz. This guide is not a legal assessment.',
    },
    link: {
      href: 'https://aik.icpraha.com/form/',
      label: { tl: 'Buksan ang orientation quiz', en: 'Open the orientation quiz' },
    },
  },
  {
    shortTitle: { tl: 'Maghanda', en: 'Prepare' },
    title: { tl: 'Ihanda ang kailangan bago mag-register', en: 'Prepare what you need before registration' },
    intro: {
      tl: 'Ilagay ang mga dokumento sa tabi mo. Huwag ilagay ang kanilang mga numero sa gabay na ito.',
      en: 'Keep these documents beside you. Do not enter their numbers into this guide.',
    },
    bullets: {
      tl: ['ePKP biometric residence card', 'Passport o EU ID na na-report sa Ministry', 'Aktibong email at phone number', 'Petsa ng kapanganakan at preferred Czech district'],
      en: ['ePKP biometric residence card', 'Passport or EU ID reported to the Ministry', 'Active email address and phone number', 'Date of birth and preferred Czech district'],
    },
  },
  {
    shortTitle: { tl: 'Mag-register', en: 'Register' },
    title: { tl: 'Gumawa ng account sa official portal', en: 'Create an account on the official portal' },
    intro: {
      tl: 'Sa susunod na link ka lamang maglalagay ng personal na impormasyon: kurzy.frs.gov.cz.',
      en: 'Enter personal information only after opening the official portal at kurzy.frs.gov.cz.',
    },
    bullets: {
      tl: [
        'Kopyahin ang first at last name nang eksakto gaya sa ePKP.',
        'Ilagay ang passport/EU ID number at ePKP number.',
        'Piliin ang nationality, preferred language at district.',
        'Basahin at tanggapin ang terms bago gumawa ng account.',
      ],
      en: [
        'Copy your first and last name exactly as shown on the ePKP.',
        'Enter the passport/EU ID number and ePKP number.',
        'Choose nationality, preferred language and district.',
        'Read and accept the terms before creating the account.',
      ],
    },
    link: {
      href: 'https://kurzy.frs.gov.cz/en/user/register',
      label: { tl: 'Buksan ang official registration', en: 'Open official registration' },
    },
  },
  {
    shortTitle: { tl: 'Magbayad', en: 'Pay' },
    title: { tl: 'Bayaran ang public course fee', en: 'Pay the public course fee' },
    intro: {
      tl: 'Pagkatapos ng registration, gagawa ang portal ng iyong payment details.',
      en: 'After registration, the portal generates your payment details.',
    },
    bullets: {
      tl: [
        'Ang public course fee ay CZK 1,500.',
        'Gamitin ang eksaktong variable symbol na ibinigay ng portal.',
        'Magbayad sa Ministry bank account sa pamamagitan ng bank transfer o postal order.',
        'Itago ang payment confirmation.',
      ],
      en: [
        'The public course fee is CZK 1,500.',
        'Use the exact variable symbol generated by the portal.',
        'Pay the Ministry account by bank transfer or postal order.',
        'Keep your payment confirmation.',
      ],
    },
    note: {
      tl: 'Huwag magbayad sa account na ipinadala sa chat o social media. Suriin lagi ang details sa official portal.',
      en: 'Do not pay an account sent through chat or social media. Always verify the details in the official portal.',
    },
  },
  {
    shortTitle: { tl: 'Pumili', en: 'Choose' },
    title: { tl: 'Pumili ng course date at location', en: 'Choose a course date and location' },
    intro: {
      tl: 'Lalabas ang available courses pagkatapos makumpirma ang bayad.',
      en: 'Available courses appear after the payment is confirmed.',
    },
    bullets: {
      tl: [
        'Pumili ng Integration Centre, petsa at oras na kaya mong puntahan.',
        'Ang kurso ay Czech na may interpreter sa mga nakalistang wika.',
        'Walang Filipino/Tagalog interpretation sa kasalukuyang official list; piliin ang English kung komportable ka rito.',
        'Tapusin ang booking hanggang makuha ang confirmation email.',
      ],
      en: [
        'Choose an Integration Centre, date and time you can attend.',
        'The course is taught in Czech with interpretation in listed languages.',
        'Filipino/Tagalog is not on the current official interpretation list; choose English if you are comfortable with it.',
        'Finish the booking and wait for the confirmation email.',
      ],
    },
    link: {
      href: 'https://kurzy.frs.gov.cz/en/user',
      label: { tl: 'Mag-log in sa official portal', en: 'Log in to the official portal' },
    },
  },
  {
    shortTitle: { tl: 'Pumunta', en: 'Attend' },
    title: { tl: 'Maghanda para sa araw ng kurso', en: 'Prepare for the course day' },
    intro: {
      tl: 'Tingnan muli ang confirmation email bago umalis.',
      en: 'Check your confirmation email again before leaving.',
    },
    bullets: {
      tl: ['Dalhin ang original ePKP residence card.', 'Pumunta sa tamang address, petsa at oras.', 'Maglaan ng apat na oras para sa buong kurso.', 'Pirmahan ang attendance sheet sa venue.'],
      en: ['Bring the original ePKP residence card.', 'Go to the correct address, date and time.', 'Allow four hours for the complete course.', 'Sign the attendance sheet at the venue.'],
    },
  },
  {
    shortTitle: { tl: 'Kumpleto', en: 'Complete' },
    title: { tl: 'Tapusin ang kurso at kunin ang certificate', en: 'Complete the course and receive the certificate' },
    intro: {
      tl: 'Kailangan mong dumalo sa buong apat na oras. Walang exam o test sa dulo.',
      en: 'You must attend the full four hours. There is no exam or test at the end.',
    },
    bullets: {
      tl: ['Kunin at itago ang attendance certificate.', 'Suriin na tama ang pangalan mo sa certificate.', 'Hindi pagtapos sa deadline ay maaaring magresulta sa fine hanggang CZK 10,000.'],
      en: ['Receive and keep the attendance certificate.', 'Check that your name is correct on the certificate.', 'Missing the deadline may result in a fine of up to CZK 10,000.'],
    },
  },
]

export const copy = {
  tl: {
    start: 'Simulan ang gabay',
    continue: 'Susunod na hakbang',
    back: 'Bumalik',
    done: 'Tapos na',
    restart: 'Magsimula ulit',
    official: 'Buksan ang official website',
    headline: 'Kumpletuhin ang iyong kurso, hakbang-hakbang',
    subhead: 'Gabay lamang ito. Walang personal na data ang kinokolekta.',
    steps: '7 hakbang',
    prepare: 'Bago ka magsimula, ihanda ang:',
    privacyTitle: 'Ligtas at pribado',
    privacy: 'Ang iyong progress lamang ang sine-save sa browser na ito. Walang passport, ePKP o contact details ang hinihingi.',
    updated: 'Batay sa official information na sinuri noong 30 Hunyo 2026.',
    source: 'Tingnan ang official course information',
  },
  en: {
    start: 'Start the guide',
    continue: 'Next step',
    back: 'Back',
    done: 'Finish guide',
    restart: 'Start again',
    official: 'Open official website',
    headline: 'Complete your course, step by step',
    subhead: 'This guide only explains the process. It does not collect personal data.',
    steps: '7 steps',
    prepare: 'Before you begin, prepare:',
    privacyTitle: 'Safe and private',
    privacy: 'Only your progress is saved in this browser. The guide never asks for passport, ePKP or contact details.',
    updated: 'Based on official information reviewed on 30 June 2026.',
    source: 'Read the official course information',
  },
}
